version: "3"
services :
  db:
    build: ./docker/db/
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=scandiwebAssignment
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image : phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1